import { jsPDF } from "jspdf";

/**
 * Minimal fee receipt PDF (A4 portrait, UTF-8 friendly for Latin text).
 */
export function downloadReceiptPdf({
  schoolName,
  receiptNumber,
  issuedAt,
  studentName,
  studentCode,
  feeName,
  amount,
  method,
  reference,
}) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  let y = 18;

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(String(schoolName || "School"), 20, y);

  y += 10;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text("Payment receipt", 20, y);

  y += 8;
  doc.setFontSize(10);
  doc.text(`Receipt no: ${receiptNumber ?? "—"}`, 20, y);
  y += 6;
  doc.text(
    `Issued: ${issuedAt ? new Date(issuedAt).toLocaleString() : "—"}`,
    20,
    y
  );

  y += 12;
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, pageW - 20, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.text("Student", 20, y);
  doc.setFont("helvetica", "normal");
  y += 6;
  doc.text(`${studentName ?? "—"} (${studentCode ?? "—"})`, 20, y);

  y += 10;
  doc.setFont("helvetica", "bold");
  doc.text("Fee", 20, y);
  doc.setFont("helvetica", "normal");
  y += 6;
  doc.text(String(feeName ?? "—"), 20, y);

  y += 10;
  doc.setFont("helvetica", "bold");
  doc.text("Amount paid", 20, y);
  doc.setFont("helvetica", "normal");
  y += 6;
  doc.text(
    amount != null ? `${Number(amount).toFixed(2)}` : "—",
    20,
    y
  );

  y += 8;
  doc.text(`Method: ${method?.trim() || "—"}`, 20, y);
  y += 6;
  doc.text(`Reference: ${reference?.trim() || "—"}`, 20, y);

  y += 14;
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("This document was generated by the school admin system.", 20, y);

  doc.save(`receipt_${String(receiptNumber ?? "export").replace(/[^\w-]+/g, "_")}.pdf`);
}
